import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import styles from "../styles/Home.module.css";
import { useContext } from "react";
import { UserContext } from "../context/User-Context";

export default function Home() {
  const { state } = useContext(UserContext);
  const { user } = state;
  console.log("index", user);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {user ? <h2>Emri Juaj : {user.fullName}</h2> : null}

        <Link href="/users/profile">
          <a>Go to profile</a>
        </Link>
      </main>
    </div>
  );
}
